### ISSUE TITLE
Не приходит код на email

### ISSUE THREAD

**Issue by JustDenP** [magersoft/muber-client#3]
Добрый день, впечатлился доработкой instaclone и использую этот проект в образовательных целях, но не могу войти, что бы посмотреть работу :( Я так понимаю что используется тестовый тариф сервиса отправки email, с привязкой только к одному email?

**Comment by magersoft** [comment]
@JustDenP Добрый день) Рад, что вам понравился проект. Я видел, что вы пытались зарегистрироваться по номеру телефону. Я использовал тестовый сервис, на котором сейчас нет средств и тестовой период закончился) Попробуйте зарегистрироваться через email. Вы получите письмо с кодом подтверждения на email! Я так же выпустил патч, который об этом сообщает на этапе регистрации

**Comment by JustDenP** [comment]
Да, я увидел патч, обрадовался что смогу посмотреть, попытался зарегистрироваться по email, но код не приходит)

**Comment by magersoft** [comment]
Только что проверил gmail и yandex, код приходит! Проверьте спам. Письмо приходит **Confirm Secret for Magergram** с почты **noreply@magergram.com**

**Comment by magersoft** [comment]
Ой, или вы пытаетесь войти в muber-client? Не обратил внимание, где открыто данное issue)

**Comment by JustDenP** [comment]
Да пришло в спам с задержкой, спасибо, пойду копаться в файлах)

**Comment by magersoft** [comment]
Отлично! happy coding 🥳
